version: '3'

services:
  backend:
    image: node:12-alpine
    depends_on: 
      - db
    volumes: 
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    # env_file: .env
    command: npm install
    command: npm run dev
    
    ports:
      - 3000:3000

  # frontend:
  #   image: node:12-alpine
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     working_dir: /usr/src/app
  #   ports:
  #     - 8080:80

  db:
    image: postgres:latest
    env_file: ./backend/.env
    ports:
      - 5432:5432